### ISSUE TITLE
Daemon Crash: "No nodes responded"

### ISSUE THREAD

**Issue by pfrazee** [andrewosh/hyperdrive-daemon#36]
I hit this crash condition when I had to reset my wifi

```
Error: No nodes responded
    at QueryStream._finalize (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:221:20)
    at QueryStream._sendUpdate (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:194:10)
    at QueryStream._moveCloser (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:207:12)
    at QueryStream._read (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:239:39)
    at QueryStream._readMaybe (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:231:70)
    at QueryStream._onresponse (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:70:12)
    at IO._finish (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/io.js:136:9)
    at IO._cancel (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/io.js:177:10)
    at IO._ontick (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/io.js:200:12)
    at listOnTimeout (internal/timers.js:531:17)"},"message":"No nodes responded","stack":"Error: No nodes responded
    at QueryStream._finalize (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:221:20)
    at QueryStream._sendUpdate (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:194:10)
    at QueryStream._moveCloser (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:207:12)
    at QueryStream._read (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:239:39)
    at QueryStream._readMaybe (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:231:70)
    at QueryStream._onresponse (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/query-stream.js:70:12)
    at IO._finish (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/io.js:136:9)
    at IO._cancel (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/io.js:177:10)
    at IO._ontick (/Users/paulfrazee/work/beaker/app/node_modules/dht-rpc/lib/io.js:200:12)
    at listOnTimeout (internal/timers.js:531:17)
```

**Comment by karlmoubarak** [comment]
I am getting the same output with the dat-sdk. 
```
Uncaught (in promise) Error: No nodes responded
    at QueryStream._finalize (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/query-stream.js:221)
    at QueryStream._sendUpdate (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/query-stream.js:194)
    at QueryStream._moveCloser (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/query-stream.js:207)
    at QueryStream._read (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/query-stream.js:239)
    at QueryStream._readMaybe (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/query-stream.js:231)
    at QueryStream._onresponse (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/query-stream.js:70)
    at IO._finish (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/io.js:157)
    at IO._cancel (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/io.js:206)
    at IO._ontick (/Users/km/Desktop/RECYCLEBIN/Dev/tryouts/recyclebin/app/node_modules/dht-rpc/lib/io.js:230)
```

I tried `npx @hyperswarm/connect-test` which should output my hole-punchability status, but it gives the following error:
```
⚠ Error while testing for connectivity Error: No nodes responded
    at QueryStream._finalize (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/query-stream.js:221:20)
    at QueryStream._sendUpdate (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/query-stream.js:194:10)
    at QueryStream._moveCloser (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/query-stream.js:207:12)
    at QueryStream._read (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/query-stream.js:239:39)
    at QueryStream._readMaybe (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/query-stream.js:231:70)
    at QueryStream._onresponse (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/query-stream.js:70:12)
    at IO._finish (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/io.js:157:9)
    at IO._cancel (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/io.js:206:10)
    at IO._ontick (/Users/km/.npm/_npx/38019/lib/node_modules/@hyperswarm/connect-test/node_modules/dht-rpc/lib/io.js:230:12)
```

Do you think we're having the same issue? Restarting my router didn't do anything. How did you end up working around this?
