### ISSUE TITLE
Crashed the daemon

### ISSUE THREAD

**Issue by okdistribute** [andrewosh/hyperdrive-daemon#55]
I've been running into a lot of issues due to having an older hyperdrive version around, but I assume I had cleared everything and came to my vps this evening to find hyperdrive-daemon had crashed:

Perhaps a known issue, or a clue? 
 
```
{"level":50,"time":1589885369015,"pid":3150,"hostname":"ubuntu-s-1vcpu-1gb-sfo2-01","name":"hyperdrive","component":"server","error":true,"err":{"type":"Error","message":"ENOMEM","stack":"Error: ENOMEM
 at sodiumBufferCopy (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/noise-protocol/handshake-state.js:180:20)
 at Object.initialize (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/noise-protocol/handshake-state.js:209:17)
 at new SimpleHandshake (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-handshake/index.js:19:22)
 at SimpleHandshake (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-handshake/index.js:8:50)
 at new ProtocolHandshake (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-hypercore-protocol/lib/handshake.js:19:18)
 at SimpleProtocol._onkeypair (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-hypercore-protocol/index.js:63:23)
 at new SimpleProtocol (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-hypercore-protocol/index.js:50:14)
 at new ProtocolStream (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/hypercore-protocol/index.js:323:18)
 at Swarm.<anonymous> (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/corestore-swarm-networking/index.js:68:30)
 at Swarm.emit (events.js:223:5)"},"message":"ENOMEM","stack":"Error: ENOMEM
 at sodiumBufferCopy (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/noise-protocol/handshake-state.js:180:20)
 at Object.initialize (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/noise-protocol/handshake-state.js:209:17)
 at new SimpleHandshake (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-handshake/index.js:19:22)
 at SimpleHandshake (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-handshake/index.js:8:50)
 at new ProtocolHandshake (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-hypercore-protocol/lib/handshake.js:19:18)
 at SimpleProtocol._onkeypair (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-hypercore-protocol/index.js:63:23)
 at new SimpleProtocol (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/simple-hypercore-protocol/index.js:50:14)
 at new ProtocolStream (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/hypercore-protocol/index.js:323:18)
 at Swarm.<anonymous> (/home/okdistribute/.nvm/versions/node/v12.14.1/lib/node_modules/hyperdrive-daemon/node_modules/corestore-swarm-networking/index.js:68:30)
 at Swarm.emit (events.js:223:5)","msg":"stopping daemon due to error","v":1}




```

**Comment by mafintosh** [comment]
@okdistribute fixed in todays release if you reinstall deps/upgrade beaker to latesr
